const songs = [
  {
    name: "Intro",
    runtime: 63,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Demon Days",
  },
  {
    name: "Last Living Souls",
    runtime: 190,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Demon Days",
  },
  {
    name: "Kids With Guns",
    runtime: 225,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Demon Days",
  },
  {
    name: "O Green World",
    runtime: 271,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Demon Days",
  },
  {
    name: "Dirty Harry",
    runtime: 223,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Demon Days",
  },
  {
    name: "Feel Good Inc.",
    runtime: 221,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Demon Days",
  },
  {
    name: "El Mañana",
    runtime: 230,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Demon Days",
  },
  {
    name: "Every Planet We Reach Is Dead",
    runtime: 293,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Demon Days",
  },
  {
    name: "November Has Come",
    runtime: 161,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Demon Days",
  },
  {
    name: "All Alone",
    runtime: 210,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Demon Days",
  },
  {
    name: "White Light",
    runtime: 128,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Demon Days",
  },
  {
    name: "Dare",
    runtime: 244,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Demon Days",
  },
  {
    name: "Fire Coming Out of the Monkey's Head",
    runtime: 196,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Demon Days",
  },
  {
    name: "Don't Get Lost In Heaven",
    runtime: 120,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Demon Days",
  },
  {
    name: "Demon Days",
    runtime: 268,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Demon Days",
  },
];

module.exports = songs;
