const songs = [
  {
    name: "Re-Hash",
    runtime: 220,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Gorillaz",
  },
  {
    name: "5/4",
    runtime: 222,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Gorillaz",
  },
  {
    name: "Tomorrow Comes Today",
    runtime: 193,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Gorillaz",
  },
  {
    name: "New Genius (Brother)",
    runtime: 239,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Gorillaz",
  },
  {
    name: "Clint Eastwood",
    runtime: 342,
    lyrics: "",
    isDeluxe: false,
    isExplicit: true,
    features: [],
    album: "Gorillaz",
  },
  {
    name: "Man Research (Clapper)",
    runtime: 272,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Gorillaz",
  },
  {
    name: "Punk",
    runtime: 98,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Gorillaz",
  },
  {
    name: "Sound Check (Gravity)",
    runtime: 282,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Gorillaz",
  },
  {
    name: "Double Bass",
    runtime: 286,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Gorillaz",
  },
  {
    name: "Rock the House",
    runtime: 249,
    lyrics: "",
    isDeluxe: false,
    isExplicit: true,
    features: [],
    album: "Gorillaz",
  },
  {
    name: "19-2000",
    runtime: 207,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Gorillaz",
  },
  {
    name: "Latin Simone (Que Pasa Contigo)",
    runtime: 218,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Gorillaz",
  },
  {
    name: "Starshine",
    runtime: 213,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Gorillaz",
  },
  {
    name: "Slow Country",
    runtime: 217,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Gorillaz",
  },
  {
    name: "M1 A1",
    runtime: 241,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Gorillaz",
  },
  {
    name: "Clint Eastwood (Ed Case / Sweetie Irie Refix)",
    runtime: 221,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Gorillaz",
  },
  {
    name: "19-2000 (Soulchild Remix)",
    runtime: 209,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Gorillaz",
  },
];

module.exports = songs;
