const songs = [
  {
    name: "Intro: I Switched My Robot Off",
    runtime: 23,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Humanz",
  },
  {
    name: "Ascension",
    runtime: 155,
    lyrics: "",
    isDeluxe: false,
    isExplicit: true,
    features: ["Vince Staples"],
    album: "Humanz",
  },
  {
    name: "Strobelite",
    runtime: 272,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Peven Everett"],
    album: "Humanz",
  },
  {
    name: "Saturnz Barz",
    runtime: 181,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Popcaan"],
    album: "Humanz",
  },
  {
    name: "Momentz",
    runtime: 196,
    lyrics: "",
    isDeluxe: false,
    isExplicit: true,
    features: ["De La Soul"],
    album: "Humanz",
  },
  {
    name: "Interlude: The Non-Conformist Oath",
    runtime: 21,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Humanz",
  },
  {
    name: "Submission",
    runtime: 201,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Danny Brown", "Kelela"],
    album: "Humanz",
  },
  {
    name: "Charger",
    runtime: 213,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Grace Jones"],
    album: "Humanz",
  },
  {
    name: "Interlude: Elevator Going Up",
    runtime: 4,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Humanz",
  },
  {
    name: "Andromeda",
    runtime: 197,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["DRAM"],
    album: "Humanz",
  },
  {
    name: "Busted and Blue",
    runtime: 277,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Humanz",
  },
  {
    name: "Interlude: Talk Radio",
    runtime: 19,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Humanz",
  },
  {
    name: "Carnival",
    runtime: 135,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Anthony Hamilton"],
    album: "Humanz",
  },
  {
    name: "Let Me Out",
    runtime: 175,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Mavis Staples", "Pusha T"],
    album: "Humanz",
  },
  {
    name: "Interlude: Penthouse",
    runtime: 11,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Humanz",
  },
  {
    name: "Sex Murder Party",
    runtime: 259,
    lyrics: "",
    isDeluxe: false,
    isExplicit: true,
    features: ["Jamie Principle", "Zebra Katz"],
    album: "Humanz",
  },
  {
    name: "She's My Collar",
    runtime: 209,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Kali Uchis"],
    album: "Humanz",
  },
  {
    name: "Interlude: The Elephant",
    runtime: 11,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Humanz",
  },
  {
    name: "Hallelujah Money",
    runtime: 263,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Benjamin Clementine"],
    album: "Humanz",
  },
  {
    name: "We Got the Power",
    runtime: 137,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Jehnny Beth"],
    album: "Humanz",
  },
  {
    name: "Interlude: New World",
    runtime: 83,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Humanz",
  },
  {
    name: "The Apprentice",
    runtime: 235,
    lyrics: "",
    isDeluxe: false,
    isExplicit: true,
    features: ["Rag'n'Bone Man", "Zebra Katz", "RAY BLK"],
    album: "Humanz",
  },
  {
    name: "Halfway to the Halfway House",
    runtime: 237,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Peven Everett"],
    album: "Humanz",
  },
  {
    name: "Out of Body",
    runtime: 224,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Kilo Kish", "Zebra Katz", "Imani Vonshà"],
    album: "Humanz",
  },
  {
    name: "Ticker Tape",
    runtime: 268,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Carly Simon", "Kali Uchis"],
    album: "Humanz",
  },
  {
    name: "Circle of Friendz",
    runtime: 129,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Brandon Markell Holmes"],
    album: "Humanz",
  },
];

module.exports = songs;
