const songs = [
  {
    name: "Orchestral Intro",
    runtime: 69,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["sinfonia ViVA"],
    album: "Plastic Beach",
  },
  {
    name: "Welcome To the World of the Plastic Beach",
    runtime: 220,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Snoop Dogg", "Hypnotic Brass Ensemble"],
    album: "Plastic Beach",
  },
  {
    name: "White Flag",
    runtime: 123,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Bashy", "Kano", "the National Orchestra For Arabic Music"],
    album: "Plastic Beach",
  },
  {
    name: "Rhinestone Eyes",
    runtime: 200,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Plastic Beach",
  },
  {
    name: "Stylo",
    runtime: 270,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Mos Def", "Bobby Womack"],
    album: "Plastic Beach",
  },
  {
    name: "Superfast Jellyfish",
    runtime: 174,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Gruff Rhys", "De La Soul"],
    album: "Plastic Beach",
  },
  {
    name: "Empire Ants",
    runtime: 283,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Little Dragon"],
    album: "Plastic Beach",
  },
  {
    name: "Glitter Freeze",
    runtime: 243,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Mark E. Smith"],
    album: "Plastic Beach",
  },
  {
    name: "Some Kind of Nature",
    runtime: 179,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Lou Reed"],
    album: "Plastic Beach",
  },
  {
    name: "On Melancholy Hill",
    runtime: 233,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Plastic Beach",
  },
  {
    name: "Broken",
    runtime: 197,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Plastic Beach",
  },
  {
    name: "Sweepstakes",
    runtime: 320,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Mos Def", "Hypnotic Brass Ensemble"],
    album: "Plastic Beach",
  },
  {
    name: "Plastic Beach",
    runtime: 227,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Mick Jones", "Paul Simonon"],
    album: "Plastic Beach",
  },
  {
    name: "To Binge",
    runtime: 235,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Little Dragon"],
    album: "Plastic Beach",
  },
  {
    name: "Cloud of Unknowing",
    runtime: 186,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Bobby Womack", "sinfonia ViVA"],
    album: "Plastic Beach",
  },
  {
    name: "Pirate Jet",
    runtime: 152,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Plastic Beach",
  },
  {
    name: "Pirate's Progress",
    runtime: 242,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Plastic Beach",
  },
  {
    name: "Three Hearts, Seven Seas, Twelve Moons",
    runtime: 134,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "Plastic Beach",
  },
];

module.exports = songs;
