const songs = [
  {
    name: "Song Machine: Strange Timez",
    runtime: 227,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Robert Smith"],
    album: "Song Machine, Season One: Strange Timez",
  },
  {
    name: "The Valley of The Pagans",
    runtime: 180,
    lyrics: "",
    isDeluxe: false,
    isExplicit: true,
    features: ["Beck"],
    album: "Song Machine, Season One: Strange Timez",
  },
  {
    name: "The Lost Chord",
    runtime: 243,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Leee John"],
    album: "Song Machine, Season One: Strange Timez",
  },
  {
    name: "Pac-Man",
    runtime: 192,
    lyrics: "",
    isDeluxe: false,
    isExplicit: true,
    features: ["ScHoolboy Q"],
    album: "Song Machine, Season One: Strange Timez",
  },
  {
    name: "Chalk Tablet Towers",
    runtime: 182,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["St. Vincent"],
    album: "Song Machine, Season One: Strange Timez",
  },
  {
    name: "The Pink Phantom",
    runtime: 253,
    lyrics: "",
    isDeluxe: false,
    isExplicit: true,
    features: ["Elton John", "6LACK"],
    album: "Song Machine, Season One: Strange Timez",
  },
  {
    name: "Aries",
    runtime: 253,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Peter Hook", "Georgia"],
    album: "Song Machine, Season One: Strange Timez",
  },
  {
    name: "Friday 13th",
    runtime: 215,
    lyrics: "",
    isDeluxe: false,
    isExplicit: true,
    features: ["Octavian"],
    album: "Song Machine, Season One: Strange Timez",
  },
  {
    name: "Dead Butterflies",
    runtime: 273,
    lyrics: "",
    isDeluxe: false,
    isExplicit: true,
    features: ["Kano", "Roxani Arias"],
    album: "Song Machine, Season One: Strange Timez",
  },
  {
    name: "Désolé",
    runtime: 333,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Fatoumata Diawara"],
    album: "Song Machine, Season One: Strange Timez",
  },
  {
    name: "Momentary Bliss",
    runtime: 221,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["slowthai", "Slaves"],
    album: "Song Machine, Season One: Strange Timez",
  },
  {
    name: "Opium",
    runtime: 410,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["EARTHGANG"],
    album: "Song Machine, Season One: Strange Timez",
  },
  {
    name: "Simplicity",
    runtime: 164,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Joan As Police Woman"],
    album: "Song Machine, Season One: Strange Timez",
  },
  {
    name: "Severed Head",
    runtime: 214,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Goldlink", "Unknown Mortal Orchestra"],
    album: "Song Machine, Season One: Strange Timez",
  },
  {
    name: "With Love To An Ex",
    runtime: 181,
    lyrics: "",
    isDeluxe: false,
    isExplicit: true,
    features: ["Moonchild Sanelly"],
    album: "Song Machine, Season One: Strange Timez",
  },
  {
    name: "MLS",
    runtime: 193,
    lyrics: "",
    isDeluxe: false,
    isExplicit: true,
    features: ["JPEGMAFIA", "CHAI"],
    album: "Song Machine, Season One: Strange Timez",
  },
  {
    name: "How Far?",
    runtime: 166,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Tony Allen", "Skepta"],
    album: "Song Machine, Season One: Strange Timez",
  },
];

module.exports = songs;
