const songs = [
  {
    name: "Phoner to Arizona",
    runtime: 254,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Fall",
  },
  {
    name: "Revolving Doors",
    runtime: 206,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Fall",
  },
  {
    name: "Hillbilly Man",
    runtime: 230,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Fall",
  },
  {
    name: "Detroit",
    runtime: 123,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Fall",
  },
  {
    name: "Shy-Town",
    runtime: 174,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Fall",
  },
  {
    name: "Little Pink Plastic Bags",
    runtime: 189,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Fall",
  },
  {
    name: "The Joplin Spider",
    runtime: 202,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Fall",
  },
  {
    name: "The Parish of Space Dust",
    runtime: 145,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Fall",
  },
  {
    name: "The Snake In Dallas",
    runtime: 131,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Fall",
  },
  {
    name: "Amarillo",
    runtime: 204,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Fall",
  },
  {
    name: "The Speak It Mountains",
    runtime: 134,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Fall",
  },
  {
    name: "Aspen Forest",
    runtime: 170,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Fall",
  },
  {
    name: "Bobby In Phoenix",
    runtime: 196,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["Bobby Womack"],
    album: "The Fall",
  },
  {
    name: "California and the Slipping of the Sun",
    runtime: 204,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Fall",
  },
  {
    name: "Seattle Yodel",
    runtime: 38,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Fall",
  },
];

module.exports = songs;
