const songs = [
  {
    name: "Humility",
    runtime: 197,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: ["George Benson"],
    album: "The Now Now",
  },
  {
    name: "Tranz",
    runtime: 182,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Now Now",
  },
  {
    name: "Hollywood",
    runtime: 293,
    lyrics: "",
    isDeluxe: false,
    isExplicit: true,
    features: ["Snoop Dogg", "Jamie Principle"],
    album: "The Now Now",
  },
  {
    name: "Kansas",
    runtime: 248,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Now Now",
  },
  {
    name: "Sorcererz",
    runtime: 180,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Now Now",
  },
  {
    name: "Idaho",
    runtime: 222,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Now Now",
  },
  {
    name: "Lake Zurich",
    runtime: 253,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Now Now",
  },
  {
    name: "Magic City",
    runtime: 239,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Now Now",
  },
  {
    name: "Fire Flies",
    runtime: 233,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Now Now",
  },
  {
    name: "One Percent",
    runtime: 141,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Now Now",
  },
  {
    name: "Souk Eye",
    runtime: 274,
    lyrics: "",
    isDeluxe: false,
    isExplicit: false,
    features: [],
    album: "The Now Now",
  },
];

module.exports = songs;
